GulAhmed.TIS/Models/ErrorViewModel.cs
namespace GulAhmed.TIS.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GulAhmed.TIS/Controllers/AccountController.cs
using GulAhmed.TIS.Core.Interface;
using Microsoft.AspNetCore.Mvc;
using static GulAhmed.TIS.Common.Helpers.Constants;

namespace GulAhmed.TIS.WEB.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountService accountService;

        public AccountController(IAccountService accountService)
        {
            this.accountService = accountService;
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string UserName, string password)
        {
            var model  = await this.accountService.ValidateUser(UserName, password);
            if (model.status == ResponseStatusCode.Succcess)
            {
                return RedirectToAction("role","setup");
            }
            return View(model);
        }
        public async  Task<IActionResult> Logout()
        {
            var model = await this.accountService.LogoutUser();
            return RedirectToAction("Login");
        }
    }
}

GulAhmed.TIS/Controllers/HomeController.cs
using GulAhmed.TIS.Core.Interface;
using GulAhmed.TIS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Oracle.ManagedDataAccess.Client;
using System.Diagnostics;

namespace GulAhmed.TIS.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserService userService;

        public HomeController(ILogger<HomeController> logger,IUserService userService)
        {
            _logger = logger;
            this.userService = userService;
        }

        public IActionResult Index()
        
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GulAhmed.TIS/Controllers/SetupController.cs
using GulAhmed.TIS.Common.Model;
using GulAhmed.TIS.Controllers;
using GulAhmed.TIS.Core.Implementation;
using GulAhmed.TIS.Core.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GulAhmed.TIS.WEB.Controllers
{
    [Authorize]
    public class SetupController : Controller
    {
        private readonly ILogger<SetupController> _logger;
        private readonly IUserService userService;
        public SetupController(ILogger<SetupController> logger, IUserService userService)
        {
            _logger = logger;
            this.userService = userService;
        }
        public IActionResult Role()
        {
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GetEmployeeDataTable(DTParameters dtparam)
        {
            var test = await userService.GetEmployeeDataTable(dtparam);
            return Json(test);
        }
        public IActionResult Customer()
        {
            return View();
        }

        public IActionResult Location()
        {
            return View();
        }
        public IActionResult Shift()
        {
            return View();
        }
 
    }
}

GulAhmed.TIS/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GulAhmed.TIS.WEB.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GulAhmed.TIS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@* <div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
 *@

GulAhmed.TIS/Views/Setup/Role.cshtml
@using GulAhmed.TIS.Common.DTO
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model IEnumerable<RoleDTO>

                    <div class="content-wrapper">
                        <!-- Content -->
                        <div class="container-xxl flex-grow-1 container-p-y">
                            <h4 class="py-3 mb-4"><span class="text-muted fw-light">Tables /</span> Basic Tables</h4>
                            <!-- Basic Bootstrap Table -->
                            <div class="card">
                                <h5 class="card-header">Table Basic</h5>
                                <div class="container">
                                    <div class="table-responsive">

                                        <table id="example" class="display" style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Role Name</th>
                                                    <th>Role Type</th>
                                                    <th>Is Active</th>
                                                    <th>Created Date</th>
                                                    <th>Update Date</th>
                                                <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tfoot>
                                                <tr>
                                                <th>ID</th>
                                                <th>Role Name</th>
                                                <th>Role Type</th>
                                                <th>Is Active</th>
                                                <th>Created Date</th>
                                                <th>Update Date</th>
                                                <th>Action</th>
                                                </tr>
                                            </tfoot>
                                        </table>

                                    </div>
                                </div>
                         </div>
                            <!--/ Basic Bootstrap Table -->

                        </div>
                    </div>

        // <div class="container-xxl flex-grow-1 container-p-y">
        //     <h4 class="py-3 mb-4"><span class="text-muted fw-light">Employee /</span> Basic Information</h4>
        //     <div class="row">
        //         <div class="col-md-12">
        //             <div class="card mb-4">
        //                 <h5 class="card-header">Employee Info</h5>
        //                 <div class="card-body">
        //                     <div>
        //                         <label for="defaultFormControlInput" class="form-label">First Name</label>
        //                         <input type="text"
        //                                class="form-control"
        //                                id="defaultFormControlInput"
        //                                placeholder="First Name"
        //                                aria-describedby="defaultFormControlHelp" />
        //                         <label for="defaultFormControlInput" class="form-label">Last Name</label>
        //                         <input type="text"
        //                                class="form-control"
        //                                id="defaultFormControlInput"
        //                                placeholder="Last Name"
        //                                aria-describedby="defaultFormControlHelp" />
        //                         <label for="defaultFormControlInput" class="form-label">Email</label>
        //                         <input type="text"
        //                                class="form-control"
        //                                id="defaultFormControlInput"
        //                                placeholder="Email"
        //                                aria-describedby="defaultFormControlHelp" />
        //                         <label for="defaultFormControlInput" class="form-label">IsActive</label>

        //                         <div class="form-check">
        //                             <input class="form-check-input" type="checkbox" value="" id="defaultCheck3" checked />
        //        >                     <label class="form-check-label" for="defaultCheck3"> Checked </label>
        //                         </div>

        //                         <div class="demo-inline-spacing" style="float:right">
        //                             <button type="button" class="btn btn-primary">Primary</button>
        //                         </div>

        //                     </div>
        //                 </div>
        //             </div>
        //         </div>





        //     </div>
        // </div


}
@section Scripts
{
    <script type="text/javascript">
 
        table = $('#example').DataTable({
            "dom": 'trip',
            "processing": true,
            "scrollX": true,
            "serverSide": true,
            "scrollCollapse": true,
            "fixedColumns": true,
            "pagingType": "full_numbers",
            "lengthMenu": [10, 25, 50],
            "table-layout": "fixed",
            "word-wrap": "break-word",
            "language": {
                "processing": "Loading"
            },
            "createdRow": function (a, b, c) {
            },
            "ajax": {
                "type": "POST",
                "url": "@Url.Action("GetEmployeeDataTable", "Setup")",
                "data": function (data) {
                    return data;
                }
            },
            "columns": [
                { "data": "seqid" },
                { "data": "role_Name" },
                { "data": "roleType" },
                { "data": "isActive" },
                { "data": "createdBy" },
                { "data": "lastUpdateDate" },
                { "data": null, "render": function (data) {
                        return '<button>Edit</button>&nbsp;<button>Delete</button>'
                } }

            ]
        });
 
    </script>

}

GulAhmed.TIS/Views/Shared/_Layout_Old.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GulAhmed.TIS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GulAhmed.TIS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GulAhmed.TIS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GulAhmed.TIS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>